In [1]:
import pandas as pd
import numpy as np

from datetime import datetime, timedelta

import itertools

In [2]:
from bs4 import BeautifulSoup as BS
import requests

In [3]:
import warnings
warnings.simplefilter(action="ignore")

In [4]:
companies = ["AMAZON", "APPLE", "GOOGLE", "META", "NETFLIX"]
    
URLS = ['https://finance.yahoo.com/quote/AMZN', 'https://finance.yahoo.com/quote/AAPL',
        'https://finance.yahoo.com/quote/GOOG', 'https://finance.yahoo.com/quote/META', 
        'https://finance.yahoo.com/quote/NFLX']

time_period = ["daily"]

In [5]:
for n, (company, period) in enumerate(list(itertools.product(companies, time_period))):
    
    date_parse = lambda dates: pd.to_datetime(dates)
    path = f"/diploma_info/datalake/raw_data/{company}_{period}.csv"

    full_set = pd.read_csv(
        path,
        parse_dates=["Date"],
        date_parser=date_parse,
        index_col=["Date"],
    )
#     .loc[:'2024-06-01']
    
    date_1 = full_set.index[-1]
    if (date_1+timedelta(days=2)).weekday() == 5 or \
       (date_1+timedelta(days=2)).weekday() == 6:
        date_2 = date_1 + timedelta(days=4)
    else:
        date_2 = date_1 + timedelta(days=2)
        
    new_dates = pd.date_range(date_1, date_2, freq='B')[1:]
    full_set = pd.concat([full_set, pd.DataFrame(None, index=new_dates)])
    
    full_set.index.name = 'date'
    full_set.columns = ["_".join(c.lower().split()) for c in full_set.columns]

    req_1 = requests.get(URLS[n])
    soup = BS(req_1.text, "html.parser")
    full_set.loc[date_2, 'open'] = float(soup.find_all('fin-streamer', class_="svelte-tx3nkj")[1].text.strip())
    full_set.loc[new_dates[0], 'open'] = full_set.shift(1).loc[new_dates[0], 'close']

        
    full_set['diff_close_value'] = full_set['close'].diff()
    full_set['diff_open_value'] = full_set['open'].diff()
    full_set['open-prev_close'] = full_set['open'] - full_set['close'].shift(1)
    full_set['(close-open)_lag_1'] = (full_set['close'] - full_set['open']).shift(1)
    
    full_set.loc[full_set[full_set['diff_close_value'] > 0].index, 'growth'] = 1
    full_set.loc[full_set[full_set['diff_open_value'] > 0].index, 'growth_open'] = 1
    full_set['growth_lag_1'] = full_set['growth'].shift(1).bfill()
    
    full_set[f'diff_open_value_mean_3_days'] = abs(full_set['diff_open_value'].rolling(window=3, closed='left').agg('mean'))
    full_set.loc[full_set['growth_open'] == 0, f'diff_open_value_mean_3_days'] = \
    -(full_set.loc[full_set['growth_open'] == 0, f'diff_open_value_mean_3_days'].values)
    full_set['new_open'] = full_set['open'].shift(1) + full_set['diff_open_value_mean_3_days']
    

    full_set['year'] = full_set.index.year
    full_set['month'] = full_set.index.month
    full_set['day'] = full_set.index.day
    full_set['day_of_week'] = full_set.index.weekday
    full_set['week_of_year'] = (full_set.index.isocalendar()['week']).astype('int')
    for i in range(1, 8):
        full_set[f'close_lag_{i}'] = full_set['close'].shift(i).bfill()
        full_set[f'volume_lag_{i}'] = full_set['volume'].shift(i).bfill()
        full_set[f'diff_close_value_lag_{i}'] = full_set['diff_close_value'].shift(i).bfill()
    full_set['growth_lag_7'] = full_set['growth'].shift(7).bfill()
    
    
    for window in [3, 5, 7]:
        close_agg = pd.DataFrame(round(full_set['close'].rolling(window=window, closed='left').agg(
            ('max', 'min', 'mean')
        )))
        close_agg.columns = [f'close_max_{window}_days', f'close_min_{window}_days', f'close_mean_{window}_days']
        
        full_set = full_set = pd.concat([full_set, close_agg], axis=1)
#         full_set = full_set.loc[:test_end.strftime("%Y%m%d"),]
      
        
    path_to_curr = f"/diploma_info/datalake/currency_rates.csv"
    currencies = pd.read_csv(
        path_to_curr,
        parse_dates=["date"],
        date_parser=date_parse,
        index_col=["date"],
    )
    
    currencies = pd.concat([currencies.dropna(), pd.DataFrame(None, index=new_dates)])
    currencies = currencies[~currencies.index.duplicated(keep='first')]
    currencies.index.name = 'date'
    
    for col in currencies.columns:
        currencies[f'{col}_lag_1'] = currencies[col].shift(1)
        currencies = currencies.drop([col], axis=1)
        
    full_set = pd.merge(full_set, currencies, on='date')    
    
    full_set = full_set.fillna(0)

    
    path_to_inf = f"/diploma_info/datalake/usa_inflation_rate.csv"
    inflation = pd.read_csv(
        path_to_inf,
        parse_dates=["date"],
        date_parser=date_parse,
        index_col=["date"],
    )
    for idx in inflation.index:
        full_set.loc[idx, 'usa_inflation_%'] = inflation.loc[idx, 'value']
    full_set = full_set.sort_index()

    full_set['usa_inflation_%'] = full_set['usa_inflation_%'].ffill()
    full_set = full_set.dropna().sort_index()   
        
    full_set.to_csv(f"/diploma_info/datalake/processed_data/{company}_{period}.csv")

In [6]:
full_set

,open,high,low,close,adj_close,volume,diff_close_value,diff_open_value,open-prev_close,(close-open)_lag_1,...,close_max_7_days,close_min_7_days,close_mean_7_days,1_USD_to_EUR_lag_1,1_EUR_to_USD_lag_1,1_UAH_to_USD_lag_1,1_USD_to_UAH_lag_1,1_EUR_to_UAH_lag_1,1_UAH_to_EUR_lag_1,usa_inflation_%
date,,,,,,,,,,,,,,,,,,,,,
2015-01-02,49.151428,50.331429,48.731430,49.848572,49.848572,13475000.0,1.047142,0.118572,0.349998,-0.231426,...,49.0,48.0,49.0,0.8265,1.2098,0.06322,15.819,19.138,0.05225,0.76
2015-01-05,49.258572,49.258572,47.147144,47.311428,47.311428,18165000.0,-2.537144,0.107143,-0.590000,0.697144,...,50.0,48.0,49.0,0.8370,1.1946,0.06265,15.962,18.900,0.05243,0.76
2015-01-06,47.347141,47.639999,45.661430,46.501431,46.501431,16037700.0,-0.809998,-1.911430,0.035713,-1.947144,...,50.0,47.0,49.0,0.8391,1.1918,0.06322,15.818,18.852,0.05305,0.76
2015-01-07,47.347141,47.421429,46.271427,46.742859,46.742859,9849700.0,0.241428,0.000000,0.845711,-0.845711,...,50.0,47.0,48.0,0.8377,1.1937,0.06317,15.830,18.896,0.05292,0.76
2015-01-08,47.119999,47.835712,46.478573,47.779999,47.779999,9601900.0,1.037140,-0.227142,0.377140,-0.604282,...,50.0,47.0,48.0,0.8461,1.1819,0.06317,15.830,18.709,0.05345,0.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-06-12,652.210022,655.780029,643.109985,650.059998,650.059998,2094400.0,1.510010,11.490051,3.660034,7.830017,...,650.0,632.0,643.0,0.9309,1.0743,0.02468,40.512,43.520,0.02298,3.27
2024-06-13,644.000000,655.250000,642.349976,653.260010,653.260010,1863600.0,3.200012,-8.210022,-6.059998,-2.150024,...,650.0,632.0,645.0,0.9249,1.0812,0.02470,40.483,43.770,0.02285,3.27
2024-06-14,655.049988,675.580017,652.640015,669.380005,669.380005,4403600.0,16.119995,11.049988,1.789978,9.260010,...,653.0,641.0,648.0,0.9312,1.0739,0.02449,40.835,43.854,0.02280,3.27
2024-06-17,669.380005,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,14.330017,0.000000,14.330017,...,669.0,641.0,651.0,0.9326,1.0723,0.02458,40.682,43.621,0.02292,3.27
2024-06-18,640.720000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,-28.660005,0.000000,0.000000,...,0.0,0.0,0.0,0.0000,0.0000,0.00000,0.000,0.000,0.00000,3.27

In [7]:
full_set.describe()

,open,high,low,close,adj_close,volume,diff_close_value,diff_open_value,open-prev_close,(close-open)_lag_1,...,close_max_7_days,close_min_7_days,close_mean_7_days,1_USD_to_EUR_lag_1,1_EUR_to_USD_lag_1,1_UAH_to_USD_lag_1,1_USD_to_UAH_lag_1,1_EUR_to_UAH_lag_1,1_UAH_to_EUR_lag_1,usa_inflation_%
count,2381.000000,2381.000000,2381.000000,2381.000000,2381.000000,2.381000e+03,2381.000000,2381.000000,2381.000000,2381.000000,...,2381.000000,2381.000000,2381.000000,2381.000000,2381.000000,2381.000000,2381.000000,2381.000000,2381.000000,2381.000000
mean,312.849126,316.990705,307.487988,312.370995,312.370995,9.225467e+06,0.260638,0.248504,0.188538,0.072003,...,322.101218,301.099118,311.626207,0.893493,1.120750,0.036240,28.368133,31.698835,0.032304,2.869164
std,166.228232,168.208120,164.014565,166.127451,166.127451,8.116137e+06,9.132850,8.910993,5.732568,6.920190,...,170.214880,161.400625,165.616023,0.046006,0.057468,0.006094,4.990591,5.009192,0.005201,2.352159
min,46.021427,0.000000,0.000000,0.000000,0.000000,0.000000e+00,-122.419983,-117.320007,-107.820007,-42.479980,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.200000
25%,152.500000,153.529999,150.119995,152.199997,152.199997,4.592500e+06,-3.130005,-3.090004,-1.059998,-2.830002,...,156.000000,146.000000,152.000000,0.862000,1.086100,0.034950,25.816000,28.711000,0.029810,1.370000
50%,321.329987,325.839996,314.519989,320.350006,320.350006,6.908900e+06,0.090012,0.139999,0.160004,-0.057137,...,332.000000,307.000000,320.000000,0.894400,1.118100,0.037010,27.019000,31.075000,0.032180,2.180000
75%,436.179993,440.799988,430.000000,434.739990,434.739990,1.117060e+07,3.680023,3.820007,1.670013,3.110001,...,446.000000,418.000000,432.000000,0.920700,1.160000,0.038720,28.600000,33.540000,0.034820,3.480000
max,692.349976,700.989990,686.090027,691.690002,691.690002,1.333875e+08,84.570038,64.419983,63.649994,55.030029,...,692.000000,663.000000,680.000000,1.042100,1.251100,0.063550,40.835000,44.054000,0.056590,9.060000

In [8]:
full_set[full_set['open-prev_close'] == full_set['open-prev_close'].min()]

,open,high,low,close,adj_close,volume,diff_close_value,diff_open_value,open-prev_close,(close-open)_lag_1,...,close_max_7_days,close_min_7_days,close_mean_7_days,1_USD_to_EUR_lag_1,1_EUR_to_USD_lag_1,1_UAH_to_USD_lag_1,1_USD_to_UAH_lag_1,1_EUR_to_UAH_lag_1,1_UAH_to_EUR_lag_1,usa_inflation_%
date,,,,,,,,,,,,,,,,,,,,,
2022-01-21,400.429993,409.149994,379.98999,397.5,397.5,58904300.0,-110.75,-117.320007,-107.820007,-9.5,...,541.0,508.0,523.0,0.8839,1.1313,0.0353,28.327,32.047,0.0312,7.04

In [9]:
full_set[~((full_set['diff_close_value'] < -15) | (full_set['diff_close_value'] > 15))] \
.mean()[['diff_close_value', 'open-prev_close', '(close-open)_lag_1']]

diff_close_value      0.177096
open-prev_close       0.199045
(close-open)_lag_1    0.107267
dtype: float64

In [10]:
full_set[~((full_set['open-prev_close'] < -10) | (full_set['open-prev_close'] > 10))] \
.mean()[['diff_close_value', 'open-prev_close', '(close-open)_lag_1']]

diff_close_value      0.269035
open-prev_close       0.217050
(close-open)_lag_1    0.113149
dtype: float64

In [11]:
full_set[~((full_set['(close-open)_lag_1'] < -15) | (full_set['(close-open)_lag_1'] > 15))] \
.mean()[['diff_close_value', 'open-prev_close', '(close-open)_lag_1']]

diff_close_value      0.348204
open-prev_close       0.238301
(close-open)_lag_1    0.050409
dtype: float64

In [12]:
full_set.new_open

date
2015-01-02     49.095712
2015-01-05     49.545237
2015-01-06     49.440000
2015-01-07     47.909046
2015-01-08     47.948570
                 ...
2024-06-12    642.109985
2024-06-13    653.153361
2024-06-14    644.996663
2024-06-17    659.826660
2024-06-18    675.103333
Name: new_open, Length: 2381, dtype: float64